PRE_GENERATED_PROMPTS = [
    # main.PROMPT_ID = 0
    {'apathetic': ['The lazy western sun', 'from a long fast,', 'choses some straw to his', 'scatters fig and taro'],
     'anxious': ['How beautiful was his heart, his bewnosing', 'nostalgic for the green cornfield and',
                 'for summer, his pensive thirst', 'ignored the tallhen, the monks, their parchterness, the fasting'],
     'embarrassed': ['.  The point, where it strikes the ground.', 'perhaps you were about to ask, what it is',
                     "that makes us famous, the fever, 'a great desire", "of which nature is never ashamed,' if your"],
     'esteemed': ['Speak out, and let thy fears be verified.', 'Milton, a name to be admired,',
                  'And still remembered, great and good,', 'Through all times, great and good,'],
     'safe': ['This is the story of a', 'piece of land that', 'and other surfaces: it', 'was calm and just as statue-'],
     'lost': ["Unemployment: Two Boys Steal Submarine's Plans,", "Stung by Black Lives Matter's Tantrums",
              'I lost my submarine.', 'It was my idea.'],
     'alone': ["Qur'an) before the life.", "You're not fit to sleep in a room alone,",
               "It's no good having a little natural beauty,", 'Or a string of white, or three black eyes,'],
     'singledout': ["But lay here every guilty subject's name,", 'O, that I were no more!, which phrase',
                    'She hath absolutely sovereign in her sight ', '*exclusive to sister but held by law'],
     'fearful': [' little Dolly leans a-steaming,', 'Smelling of boot and bubblegum.', 'But that is not the worst.',
                 'Now to add a new and fearful'],
     'fearless': ['For those in danger; then they tell', 'The danger in the danger. When the man',
                  'Has turned his back, and is serving out', 'A life for death, while his brave comrades'],
     'lustful': ['The heart, till now a solitary thing', 'Of light involvement only, she moved all night',
                 'Until she dwelt with her so passionate and strong', 'Defiled, defiled, her blind and naked heart'],
     'hated': ['How beautiful was his heart, his bewnosing', 'nostalgic for the green cornfield and',
               'for summer, his pensive thirst', 'ignored the tallhen, the monks, their parchterness, the fasting'],
     'independent': ['Evermore they were on guard,', 'Hemming the strong hands of the',
                     'Warding the houses from sudden raiders;', 'Till one by one they fell in the'],
     'free': [", chas'd with crimson salt,--", 'The strong doctor (whom I must excuse',
              'For stealing from his village, free to buy,', "He also showed us, as we'll not soon forget,"],
     'attracted': ['When love in its majestic naivete', "Dew'd the strings until their changeful melody,",
                   'Crafts of praise an artless music made the keen', 'And glittering passion audible, while'],
     'happy': ['He gave it to me and said he', '"Was he not a man, with a busy life',
               'And affairs of greater weight than our playful glee?', 'The men that die young in our Republic'],
     'sad': [' muttered dreary, long,', 'Long dreary dreary dreary,', 'Long dreary dreery dreery,',
             'Long dreest to a treble of treble,'],
     'derailed': ['Did such only for their sake, who teach', 'The idle, pleased, to live disjointed,',
                  'And selfishly give themselves the care,', 'And other people none?'],
     'average': [' home that he saw,', 'Exchanged those smiles and fleeting glances,',
                 'That common oaths and vows annulled,', 'And called for what was left of grace.'],
     'powerless': ['By blameworthy intention on the part of the fowler.',
                   'There is no deadly poison that falls without atonement,',
                   'Without atonement; yet so great are the deadly poisons,',
                   'For the reckless have no defense from fillip.'],
     'attached': ['A woman speaking, in a low voice,', 'In the one language understood by all,',
                  'And all can see the truth in her eyes.', 'He brought her to the place where the'],
     'angry': ['"Bhmahga-Matújuśa", by Glyn Hughton [Mythology, Fairy-tales & Legends]', 'prayed close with closed',
               'hymns of storm and prayer', 'were mad and rampant as'],
     'loved': ['Because they would never agree I had to', 'Till I was entrusted with', 'Such a colossal understatement',
               'as to appear ignorant.'],
     'cheated': ['that is yet to be.', 'them so plainly myself I thought them the necessary',
                 'mind that reads them not counters moving them. And',
                 'perjuries, and accused them falsely, and I did bind'],
     'surprise': ['One day he entered a room', 'He thought was an ordinary-sized room,',
                  'And, startled, found he was inside a cage,', 'The female of the household.']},
    # main.PROMPT_ID = 1
    {'apathetic': ['The lazy western sun', 'from a long fast,', 'choses some straw to his', 'scatters fig and taro']}
]